---
apiVersion: v1
kind: Namespace
metadata:
  name: dcs
  labels:
    name: dcs
    app.kubernetes.io/name: dcs
    app.kubernetes.io/part-of: cps-enterprise-dcs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcs-config
  namespace: dcs
data:
  POSTGRES_DB: dcs_eventstore
  POSTGRES_USER: dcs_admin
  REDIS_URL: redis-master:6379
  KAFKA_BROKERS: kafka:9092

---
apiVersion: v1
kind: Secret
metadata:
  name: dcs-secrets
  namespace: dcs
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES"
  REDIS_PASSWORD: "CHANGE_ME_REDIS"
  VAULT_TOKEN: "CHANGE_ME_VAULT"
  GRAFANA_PASSWORD: "CHANGE_ME_GRAFANA"
