// Code generated by protoc. DO NOT EDIT.
// Master Agent v1 Protocol Buffers

package proto

import (
	"fmt"
)

func init() {
	if p, ok := interface{}(nil).(interface{ Is(fmt.Scanner) bool }); !ok || !p.Is(nil) {
		panic("package proto: pb.go missing imports")
	}
}

// Placeholder: run `make proto` or protoc to regenerate
// master_agent_v1.pb.go from master_agent_v1.proto
